spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hearts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: 50645367556B58703273357638792F423F4528482B4D6251655468576D597133

client:
  url: http://localhost:4200
  api-url-pattern: /api/v1/**