spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hearts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret-key: 50645367556B58703273357638792F423F4528482B4D6251655468576D597133

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: src/main/resources/keystore/hearts-tls.p12
    key-store-password: hearts@123
    key-alias: hearts-tls
    key-password: hearts@123
  port: 8080
